# Change these first
owner: Zaid-maker # Your GitHub organization or username, where this repository lives
repo: status-page-advanced # The name of this repository

sites:
  - name: DevMirza Blog
    url: https://blog.cyclonebotlist.ml
  - name: DevMirza Blog Backend
    url: https://waggish-tangible-airport.strapiapp.com
  - name: Chat Bot API
    url: https://codex-api.cyclonebotlist.ml
  - name: Black Fort Hosting
    url: https://blackforthosting.com
  - name: Cyclone Bot List (domain not working)
    url: http://n2.danbot.host:2427
  - name: Cyclone Server List
    url: https://cyclone-server-list.glitch.me

status-website:
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status-page.cyclonebotlist.ml
  # baseUrl: /status-page-advanced
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is the status page for DevMirza Services Monitoring, Powered by **Upptime**.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
