owner: Zaid-maker
repo: status-page-advanced
user-agent: Zaid-maker

sites:
  - name: Vercel
    url: https://vercel.com
  - name: Next.js
    url: https://nextjs.org
  - name: Turbo
    url: https://turbo.build
  - name: Chat Bot API
    url: https://codex-api.zaidmaker.repl.co
  - name: AI 3D API
    url: https://rose-sleepy-elk.cyclic.app
  - name: Black Fort Hosting
    url: https://blackforthosting.com
  #- name: Cyclone Server List
  #  url: https://cyclone-server-list.glitch.me
  - name: Discord Bot List
    url: https://rough-freckle-ball.glitch.me/
  - name: Google DNS 1
    check: "tcp-ping"
    url: 8.8.4.4
    port: 53
  - name: Google DNS 2
    check: "tcp-ping"
    url: 8.8.8.8
    port: 53
  - name: Code Server
    check: "tcp-ping"
    url: pnode2.danbot.host
    port: 2916

status-website:
  theme: ocean
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status-page.cyclonebotlist.ml
  baseUrl: /status-page-advanced
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: DevMirza
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is the status page for DevMirza Services Monitoring, Powered by **Upptime**.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
