# Change these first
owner: Zaid-maker # Your GitHub organization or username, where this repository lives
repo: status-page-advanced # The name of this repository

sites:
  - name: Google
    url: https://google.com
  - name: Google Cloud
    url: https://console.cloud.google.com
  - name: Chat Bot API
    url: https://codex-api.zaidmaker.repl.co
  - name: Black Fort Hosting
    url: https://blackforthosting.com
  - name: Cyclone Bot List
    url: https://cyclonebotlist.ml
  - name: Cyclone Server List
    url: https://cyclone-server-list.glitch.me
  - name: Google DNS 1
    check: "tcp-ping"
    url: 8.8.4.4
    port: 53
  - name: Code Server TCP
    check: "tcp-ping"
    url: pnode1.danbot.host
    port: 1572

status-website:
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status-page.cyclonebotlist.ml
  # baseUrl: /status-page-advanced
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: DevMirza
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is the status page for DevMirza Services Monitoring, Powered by **Upptime**.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
